name: Build OpenWrt  # 工作流名称

on:
  workflow_dispatch:
    inputs:
      install_quickfile:
        description: '是否安装 Quickfile 插件'
        required: false
        default: 'true'

jobs:
  build:
    runs-on: ubuntu-22.04  # 或你的运行环境
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # 下面是你要修改的部分
      - name: Run DIY Part 1
        if: github.event.inputs.install_quickfile == 'true'
        run: |
          # 删除 Windows 换行符
          sed -i 's/\r$//' Auto-OpenWrt-build-x86-64.sh
          
          chmod +x diy-part1.sh
          cp diy-part1.sh imagebuilder/
          cd imagebuilder

      - name: Update Feeds
        run: ./scripts/feeds update -a
